path: C:/dragon egg/AnimalDetectionYolo/data            #dataset root dir
train: images/train           #train images rel
val:  images/val            #val images rel

#classes
names:
    0: 'empty'
    1: 'White-lipped peccary'
    2: 'Central American agouti'
    3: 'Lowland paca'
    4: 'Cougar'
    5: 'South American tapir'
    6: 'Collared peccary'
    7: 'Red brocket deer'
    8: 'Ocelot'
    9: 'Ruddy quail-dove'
    10: 'South American coati'
    11: 'Nine-banded armadillo'
    12: 'Tayra'
    13: 'Common opossum'
    14: 'Crab-eating raccoon'
    15: 'Jaguar'
    16: 'Giant anteater'
    17: 'Great tinamou'
    18: 'Brazilian rabbit'
    19: 'Jaguarundi'
    20: 'Margay'
    21: 'Gray brocket deer'
    22: 'Gray four-eyed opossum'
    23: 'Wild goat'
    24: 'Domestic cattle'
    25: 'Domestic sheep'
    26: 'Gray wolf'
    27: 'Scrub hare'
    28: 'Emerald-spotted wood dove'
    29: 'Olive baboon'
    30: 'Common genet'
    31: 'Bushbuck'
    32: 'African wild ass'
    33: 'Slender mongoose'
    34: 'African bush elephant'
    35: 'Gambian pouched rat'
    36: 'Steenbok'
    37: 'Striped hyena'
    38: 'Impala'
    39: 'Spotted hyena'
    40: 'Caracal'
    41: 'Wild horse'
    42: 'Lion'
    43: 'Eland'
    44: 'Waterbuck'
    45: 'Warthog'
    46: 'Leopard'
    47: 'White-tailed mongoose'
    48: 'Black-backed jackal'
    49: 'African buffalo'
    50: 'Plains zebra'
    51: 'Giraffe'
    52: 'Hartebeest'
    53: 'Vervet monkey'
    54: 'Guenther dik-dik'
    55: 'Bushpig'
    56: 'Grant gazelle'
    57: 'Thomson gazelle'
    58: 'Ostrich'
    59: 'Aardvark'
    60: 'Cheetah'
    61: 'White-bellied bustard'
    62: 'Wildcat'
    63: 'Beisa oryx'
    64: 'Buff-crested bustard'
    65: 'Kori bustard'
    66: 'Dwarf mongoose'
    67: 'Black-bellied bustard'
    68: 'Great argus'
    69: 'Leopard cat'
    70: 'Banded palm civet'
    71: 'Indian muntjac'
    72: 'Wild boar'
    73: 'Sun bear'
    74: 'Sambar deer'
    75: 'Malayan porcupine'
    76: 'Asian golden cat'
    77: 'Tiger'
    78: 'Three-striped ground squirrel'
    79: 'Emerald dove'
    80: 'Blotched genet'
    81: 'Crested porcupine'
    82: 'African wild dog'
    83: 'Rock hyrax'
    84: 'Laughing dove'
    85: 'Striped polecat'
    86: 'Domestic dog'
    87: 'Unknown bird'
    88: 'Blue-crowned motmot'
    89: 'Gray-winged trumpeter'
    90: 'Nocturnal curassow'
    91: 'Black agouti'
    92: 'Green acouchi'
    93: 'Spiny rat'
    94: 'White-nosed coati'
    95: 'Northern tamandua'
    96: 'Opossum species'
    97: 'Crested guan'
    98: 'Eagle species'
    99: 'Dwarf caiman'
    100: 'Dromedary camel'
    101: 'Bat-eared fox'
    102: 'Vulturine guineafowl'
    103: 'Grevy zebra'
    104: 'Aardwolf'
    105: 'Serval'
    106: 'Greater kudu'
    107: 'Hippopotamus'
    108: 'Spotted thick-knee'
    109: 'Unstriped ground squirrel'
    110: 'Masked palm civet'
    111: 'Marbled cat'
    112: 'Dhole'
    113: 'Water monitor'
    114: 'Yellow-throated marten'
    115: 'Banded linsang'
    116: 'Crested partridge'
    117: 'Sumatran pheasant'
    118: 'Bronze-tailed peacock-pheasant'
    119: 'Sunda pangolin'
    120: 'Sumatran serow'
    121: 'Macaque species'
    122: 'Noble francolin'
    123: Hoest monkey'
    124: 'Black-fronted duiker'
    125: 'African brush-tailed porcupine'
    126: 'Chimpanzee'
    127: 'Blue monkey'
    128: 'Carruthers mountain squirrel'
    129: 'Yellow wagtail'
    130: 'Yellow-whiskered greenbul'
    131: 'Little greenbul'
    132: 'Delicate thicket rat'
    133: 'Forest giant squirrel'
    134: 'Boehm bush squirrel'
    135: 'Yellow-backed duiker'
    136: 'Rusty-bellied brush-furred rat'
    137: 'Striped grass mouse'
    138: 'Gosling striped mouse'
    139: 'Stella wood mouse'
    140: 'Servaline genet'
    141: 'Side-striped jackal'
    142: 'Fischer turaco'
    143: 'Pygmy mouse'
    144: 'Ross turaco'
    145: 'Tambourine dove'
    146: 'Tullberg soft-furred mouse'
    147: 'Long-footed rat'
    148: 'White-headed buffalo weaver'
    149: 'Egyptian goose'
    150: 'Link rat'
    151: 'Red-necked francolin'
    152: 'African palm civet'
    153: 'Gray-headed woodpecker'
    154: 'Olive thrush'
    155: 'Dusky turtle dove'
    156: 'Brocket deer species'
    157: 'Gray fox'
    158: 'Ocellated turkey'
    159: 'Great curassow'
    160: 'Paca'
    161: 'Baird tapir'
    162: 'Raccoon'
    163: 'White-tailed deer'
    164: 'Gray-headed dove'
    165: 'Central American red brocket'
    166: 'Striped hog-nosed skunk'
    167: 'Yucatan brown brocket'
    168: 'Plain chachalaca'
    169: 'Thomas langur'
    170: 'Sunda clouded leopard'
    171: 'Hog badger'
    172: 'Chevrotain species'
    173: 'Sumatran treepie'
    174: 'Sumatran blue flycatcher'
    175: 'Malayan weasel'
    176: 'Javan whistling thrush'
    177: 'Sumatran partridge'
    178: 'Siberian blue robin'
    179: 'Pheasant species'
    180: 'Javan blue whistling thrush'
    181: 'Red-billed junglefowl'
    182: 'Crested serpent eagle'
    183: 'Blue whistling thrush'
    184: 'Collared mongoose'
    185: 'Lesser short-tailed swift'
    186: 'Crab-eating fox'
    187: 'Motorcycle'
    188: 'Deer mouse species'
    189: 'Jaguarundi'
    190: 'Bare-throated tiger heron'
    191: 'Coyote'
    192: 'Blue ground dove'
    193: 'Squirrel species'
    194: 'Unknown bird'
    195: 'Gray-necked wood rail'
    196: 'Limpkin'
    197: 'Central American red brocket'